name: CI/CD

on:
  push:
    branches: [ "master", "develop", "feature/*" ] # Run on pushes to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test